server:
  port: 8082
logging:
  level:
    ROOT: INFO
spring:
  application:
    admin:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: info, health, beans


logpassmapclass:
  logPassMap:
    Lennon:   112374
    Ringo:    231453
    McCarney: 342514
    Harrison: 515142