server:
  port: 8082
logging:
  level:
    ROOT: INFO
spring:
  application:
    admin:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: info, health, beans

message: "Test Props msg"

messager:
  message: "Hello from Starter"